#!/bin/bash
echo "total 16                                                                                                                                
-rwxrwxrwx 1 root root 73 Jul  3 02:31 0-current_working_directory                                                                            
-rw-r--r-- 1 root root 66 Jul  3 02:48 1-listit                                                                                               
-rw-r--r-- 1 root root 25 Jul  3 03:15 2-bring_me_home                                                                                      
-rw-r--r-- 1 root root 11 Jul  3 10:57 3-listfiles"
